#===datasource start===
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
#===datasource end===

#===druid start===
  druid:
    initial-size: 5 #连接池初始化大小
    min-idle: 10 #最小空闲连接数
    max-active: 20 #最大连接数
    web-stat-filter:
      exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
    #访问监控网页的登录用户名和密码
    stat-view-servlet:
      login-username: druid
      login-password: druid
#===druid end===

logging:
  path: /var/logs #配置日志生成路径