#===server start===
server:
  port: 8085
#===server end===

#配置日志生成路径
logging:
  path: /var/logs

#===datasource start===
spring:
  datasource:
    url: jdbc:mysql://db:3306/mall?useUnicode=true&characterEncoding=utf-8
    username: reader
    password: 123456
#===datasource end===

#===druid start===
  druid:
    initial-size: 5 #连接池初始化大小
    min-idle: 10 #最小空闲连接数
    max-active: 20 #最大连接数
    web-stat-filter:
      exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
    #访问监控网页的登录用户名和密码
    stat-view-servlet:
      login-username: druid
      login-password: druid
#===druid end===

#===mongodb start===
  data:
    mongodb:
      host: mongo
      port: 27017
      database: mall-port
#===mongodb end===

#===rabbitMq start===
  rabbitmq:
    host: rabbitmq
    port: 5672
    virtual-host: /mall
    username: mall
    password: mall
    publisher-confirms: true #如果对异步消息需要回调必须设置为true
#===rabbitMq end===

#===redis start===
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: redis # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
    timeout: 0 # 连接超时时间（毫秒）
#===redis end===
